### ISSUE TITLE
Sometimes Geth does not start properly

### ISSUE THREAD

**Issue by jbaldwinroberts** [CameronDiver/RunEthereumMiner#6]

**Comment by jbaldwinroberts** [comment]
Traceback (most recent call last):
  File "runminer.py", line 139, in <module>
    geth.killGeth()
  File "/home/joseph/git/RunEthereumMiner/gethmarshal.py", line 66, in killGeth
    self.thread.process.wait()
AttributeError: 'GethThread' object has no attribute 'process'
Killing Geth...
Exception AttributeError: "'GethThread' object has no attribute 'process'" in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

**Comment by CameronDiver** [comment]
Has this happened with the new version?

**Comment by josephroberts** [comment]
Yeah it happens on the current version. It disappears for like half a
second every 10 seconds or so.

**Comment by jbaldwinroberts** [comment]
yes

**Comment by jbaldwinroberts** [comment]
I think this error happens when Geth does not start up properly and thus can not be killed. I've noticed this a few times now. I'll try to get the console log.

**Comment by jbaldwinroberts** [comment]
Here is an example

```
joseph@joe-ubuntu:~/git/RunEthereumMiner$ python runminer.py --geth="../go-ethereum/build/bin/geth" --ethminer="/usr/bin/ethminer"
[20:18  info]       Running command '../go-ethereum/build/bin/geth --rpccorsdomain localhost --rpc --autodag'
[20:18  info]       Running command '/usr/bin/ethminer'
[20:18  ethminer]   Connected.
[20:19  ethminer]   Full DAG loaded
[20:19  ethminer]   Average Speed: 81.775KH/s^C
Received keyboard interrupt, stopping processes...
Please wait to avoid ethereum directory corruption.
Traceback (most recent call last):
  File "runminer.py", line 141, in <module>
    geth.killGeth()
  File "/home/joseph/git/RunEthereumMiner/gethmarshal.py", line 108, in killGeth
    self.thread.process.wait()
AttributeError: 'GethThread' object has no attribute 'process'
Killing Geth...
Exception AttributeError: "'GethThread' object has no attribute 'process'" in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
```

Geth has not started.

**Comment by CameronDiver** [comment]
It's also a bug in the gethmarshal class as well, the changes im making to the class should fix it but it's not quite working yet
